
# SEO settings
title: Simplest
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://nandomoreira.me
baseurl: "/simplest"
# baseurl: null

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/simplest
disqus_shortname: "nandothemes"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Amber Marie Boyd
  job      : Linguist
  bio      : ""
  thumb    : /images/author.jpg
  email    : amb698@cornell.edu
  url      : http://amberie.github.io
  github   : http://github.com/nandomoreirame
  twitter  : 
  facebook : 
  linkedin : http://linkedin.com/in/amberie

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
